/**
 * ============================
 * System Error Code
 * ============================
 */
export enum ErrorCode {
  /* =========================
   * Authentication / Session
   * ========================= */
  AUTH_REQUIRED = 'AUTH_REQUIRED', // No token
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  SESSION_EXPIRED = 'SESSION_EXPIRED', // tokenVersion mismatch
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_APPROVED = 'ACCOUNT_NOT_APPROVED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  AUTH_METHOD_NOT_AVAILABLE = 'AUTH_METHOD_NOT_AVAILABLE',
  PASSWORD_NOT_SET = 'PASSWORD_NOT_SET',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  /* =========================
   * Authorization
   * ========================= */
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',

  /* =========================
   * Identity
   * ========================= */
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  MOBILE_ALREADY_EXISTS = 'MOBILE_ALREADY_EXISTS',
  NID_ALREADY_EXISTS = 'NID_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  /* =========================
   * Validation
   * ========================= */
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  /* =========================
   * Jobs / Booking
   * ========================= */
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  SQUARE_FOOTAGE_REQUIRED = 'SQUARE_FOOTAGE_REQUIRED',
  PROVIDER_NOT_ELIGIBLE = 'PROVIDER_NOT_ELIGIBLE',
  JOB_ACCESS_DENIED = 'JOB_ACCESS_DENIED',

  /* =========================
   * Payments / Wallet
   * ========================= */
  PAYMENT_ALREADY_EXISTS = 'PAYMENT_ALREADY_EXISTS',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_STATE = 'INVALID_PAYMENT_STATE',
  TRANSACTION_ID_REQUIRED = 'TRANSACTION_ID_REQUIRED',
  PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE',
  NO_MFS_ACCOUNT = 'NO_MFS_ACCOUNT',
  WITHDRAWAL_MIN_AMOUNT = 'WITHDRAWAL_MIN_AMOUNT',
  INSUFFICIENT_WALLET_BALANCE = 'INSUFFICIENT_WALLET_BALANCE',
  COMMISSION_RULE_CONFLICT = 'COMMISSION_RULE_CONFLICT',

  /* =========================
   * System
   * ========================= */
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}

